services:
  - type: web
    name: builditrecords-api
    env: node
    plan: free
    rootDir: server
    buildCommand: echo "No build required"
    startCommand: node server-only.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true
