services:
  - type: web
    name: builditrecords-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "https://builditrecords.com,https://www.builditrecords.com,https://*.vercel.app"
    autoDeploy: true
