services:
  - type: web
    name: builditrecords-api
    env: node
    plan: free
    buildCommand: npm install && npm run build:render
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PORT
        value: 3001
    autoDeploy: true
