services:
  - type: web
    name: builditrecords-api
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install express cors
    startCommand: node minimal.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: "*"
    autoDeploy: true
